#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define SCREEN_WIDTH 512
#define SCREEN_HIGHT 435
#define MOVEMENTSPEED 0.05f
#define JUMP_FORCE_DECREMENT 300.0f
#define INITAL_JUMP_FORCE 300.0f
#define GRAVITY 60.0f 
#define MAP_HEIGHT 13
#define MAP_WIDTH 16
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define SCREENSHAKE_DURATION  4.0f
#define KOOPA_INJURED_TIME 10.0f
#define KOOPA_SPEED 0.05f
#define INITAL_JUMP_FORCE_SMALL 10.0f;

#endif