#pragma once

#define SCREEN_WIDTH 512
#define SCREEN_HIGHT 416
#define MOVEMENTSPEED 0.2f
#define JUMP_FORCE_DECREMENT 96.0f
#define INITAL_JUMP_FORCE 96.0f
#define GRAVITY 0.1f 
#define MAP_HEIGHT 13
#define MAP_WIDTH 16
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define SCREENSHAKE_DURATION  0.25f
#define KOOPA_INJURED_TIME 10.0f
#define KOOPA_SPEED 0.2f
#define INITAL_JUMP_FORCE_SMALL 10.0f;